FROM node:18-alpine as build
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app                         
RUN npm run build
# production environment
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

COPY --from=build /app/build/ /usr/share/nginx/html/messenger
COPY --from=build /app/build/*.html /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]